# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3e5306e565a353fd19c65495b1a968ce92bb3708e7d66215671d2a422b4c822ad461ef708b9bd2d2f6cc0e2f27d30f25dbc03f2c89ce3a9f2f81544af832e3a

test:
  secret_key_base: d89171bb77dc55975fbf9665b444e726efe1d9800e150f013f16b8afc04758ef9423c77233361afedb82b584782767f5eb87f596ffe2eb7859fbd25e5e688e81

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
